on:
  pull_request:
  push:
    branches:
      - main

name: Editorconfig Linter

jobs:

  tests:
    name: "Run Lint on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ 'ubuntu-latest' ]
    steps:
      - uses: actions/checkout@v3
      - uses: editorconfig-checker/action-editorconfig-checker@main
      - run: editorconfig-checker

