# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

on:
  pull_request:
  push:
    branches:
      - main

name: Tests

jobs:

  tests:
    name: "Run all tests on Ubuntu"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ 'ubuntu-latest', 'macos-latest' ]
    steps:
      - uses: actions/checkout@v3
      - name: "Tests"
        run: "make test"
