name: Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  tests:
    name: "Run tests on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - alpine-latest
          - macos-latest
          - windows-latest
        include:
          - os: windows-latest
            script_name: 'bash -c "./bashunit -e tests/globals.sh tests/**/*_test.sh"'
          - os: macos-latest
            script_name: 'make test'
          - os: ubuntu-latest
            script_name: 'make test'
          - os: alpine-latest
            script_name: 'make test'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies on Alpine
        if: matrix.os == 'alpine-latest'
        run: |
          apk add bash make shellcheck git curl perl

      - name: Run Tests
        run: ${{ matrix.script_name }}
