name: Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:

  simple-output:
    name: "${{ matrix.os }} - simple & sync"
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Tests
        run: |
          ./bashunit --simple --no-parallel tests/

  simple-output-parallel:
    name: "${{ matrix.os }} - simple & parallel"
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Tests
        run: |
          ./bashunit --simple --parallel tests/

  detailed-output-parallel:
    name: "${{ matrix.os }} - detailed & parallel"
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Tests
        run: |
          ./bashunit --detailed --parallel tests/

  windows:
    name: "windows (${{ matrix.test_chunk }})"
    timeout-minutes: 10
    runs-on: windows-latest
    strategy:
      matrix:
        test_chunk: [acceptance, functional, unit]
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run tests
        shell: bash
        run: |
          ./bashunit tests/${{ matrix.test_chunk }}/*_test.sh

  alpine:
    name: "alpine-latest"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Tests
        run: |
          docker run --rm -v "$(pwd)":/project alpine:latest /bin/sh -c " \
            apk update && \
            apk add --no-cache bash make git && \
            adduser -D builder && \
            chown -R builder /project && \
            su - builder -c 'cd /project; make test';"
