name: Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  tests:
    name: "Tests on ${{ matrix.os }} (${{ matrix.test_chunk }})"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        test_chunk: [acceptance, functional, unit]
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Tests
        shell: bash
        run: |
          ./bashunit -e tests/bootstrap.sh tests/${{ matrix.test_chunk }}/*_test.sh

  simple-output:
    name: "Tests simple output"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Tests
        run: |
          ./bashunit -e tests/bootstrap.sh --simple tests/

  alpine:
    name: "Tests on alpine-latest"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Tests
        run: |
          docker run --rm -v "$(pwd)":/project alpine:latest /bin/sh -c " \
            apk update && \
            apk add --no-cache bash make git && \
            adduser -D builder && \
            chown -R builder /project && \
            su - builder -c 'cd /project; make test';"
