name: Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  tests:
    name: "Run ${{ matrix.test_chunk }} tests on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        test_chunk: [acceptance, functional, unit]
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
      fail-fast: false
      max-parallel: 3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up shell for Windows
        if: matrix.os == 'windows-latest'
        run: echo "Using bash as shell"
        shell: bash

      - name: Run tests
        shell: bash
        run: |
          set -e  # Exit on error
          if [ -d tests/${{ matrix.test_chunk }} ]; then
            ./bashunit -e tests/bootstrap.sh tests/${{ matrix.test_chunk }}/*_test.sh
          else
            echo "Test directory tests/${{ matrix.test_chunk }} not found!"
            exit 1
          fi

  simple-output:
    name: "Tests simple output"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Tests
        run: |
          ./bashunit -e tests/bootstrap.sh --simple tests/

  alpine:
    name: "Tests on alpine-latest"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Tests
        run: |
          docker run --rm -v "$(pwd)":/project alpine:latest /bin/sh -c " \
            apk update && \
            apk add --no-cache bash make git && \
            adduser -D builder && \
            chown -R builder /project && \
            su - builder -c 'cd /project; make test';"
