name: Tests

on:
  pull_request:
  push:
    branches:
      - main
jobs:
  tests:
    name: "Run tests on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Tests (Windows)
        if: runner.os == 'Windows'
        shell: bash
        run: ./bashunit -e tests/bootstrap.sh tests/**/*_test.sh

      - name: Run Tests (Linux/macOS)
        if: runner.os != 'Windows'
        run: make test

  simple-output:
    name: "Run tests with simple output"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Tests
        run: |
          ./bashunit -e tests/bootstrap.sh --simple tests/

  alpine:
    name: "Run tests on alpine-latest"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Tests
        run: |
          docker run --rm -v "$(pwd)":/project alpine:latest /bin/sh -c " \
            apk update && \
            apk add --no-cache bash make git && \
            adduser -D builder && \
            chown -R builder /project && \
            su - builder -c 'cd /project; make test';"
